### ISSUE TITLE
Add washizu mode

### ISSUE THREAD

**Issue by not-nocturnal** [riichinomics/autotable#2]
The general idea would be:

- Washizu Box that can hold all the tiles
- Automatic shuffle of the box after drawing a tile from it
- Manual shuffle button
- Washizu tile skin (double-sided is likely easiest, and best from a readability standpoint)

But I'm also wondering if post-draw shuffle is worth it. Could just have it shuffle before drawing from it, removing the need for a manual shuffle entirely. Would mean if you drop your tile in by accident, there's no easy getting it back, but that's kinda how it'd be in real life anyway.

**Comment by riichinomics** [comment]
Done
