### ISSUE TITLE
Correct contact info on About page

### ISSUE THREAD

**Issue by pwmarcz** [riichinomics/autotable#27]
Hi! Original author here. I just received an email with feature request to https://autotable.riichi.moe/, and of course I'm not able to help them, so I redirected them to this Github project.

It seems that the about page (https://autotable.riichi.moe/about.html) still lists only my email - could you edit it to include your contact info / link to the Github project, and perhaps an information that this is a fork?

Thanks in advance! It's great to see this project grow.

**Comment by riichinomics** [comment]
Yeah sorry about that. I'll probably be working on autotable more this year
so I'll do it at that time. Please forward the email to me in the meantime.

**Comment by riichinomics** [comment]
@pwmarcz let me know if you're unhappy with attributions, I've left most of it intact just changes some links.
